### PR TITLE
Update mergify config to use queue instead of merge.

### PR DESCRIPTION
**Pull request by jguiditta**
The old way of configuring merges has been deprecated since June
2021[1], so we need to move to the newer syntax.

[1] https://blog.mergify.com/strict-mode-deprecation/

Signed-off-by: Jason Guiditta <jguiditt@redhat.com>

### CODE REVIEW

**Review by fuzzball81 — DISMISSED** [review]

**Review by jpichon — COMMENTED** [review]
I'm not sure I see much use in changing only the 'strict' condition without changing to github actions since this can't pass either way... Should we just drop the travis config lines for now and move the number of approvals to two as well?

**Comment by jguiditta** [comment]
> I'm not sure I see much use in changing only the 'strict' condition without changing to github actions since this can't pass either way... Should we just drop the travis config lines for now and move the number of approvals to two as well?

I made that a TODO in the mergify file in order to keep these tasks tightly scoped.  I am going to add a separate ticket to switch this to github actions, and will squeeze it in after my next task, if there is time.

**Comment by jguiditta** [comment]
Hmm, thinking a bit more, I suppose there would be no harm in dropping the travis requirement in this patch, since it wont ever pass, and upping the reviewers to >=2, but leave the github actions for a separate patch, as planned

**Review by fuzzball81 — APPROVED** [review]

**Review by jpichon — APPROVED** [review]
Thanks! LGTM

**Pull request merged**
